### ISSUE TITLE
Referenced before assignment error in nested try-except

### ISSUE THREAD

**Issue by stveit** [SUNET/cnaas-nms#220]
**Describe the bug**
When running a repository refresh for setting, we get this error message.

```
{
  "status": "error",
  "message": "Error in repository: local variable 'e' referenced before assignment"
}
```

Using the logs we traced it to settings.py line 255 (in check_settings_syntax). We believe it is caused by the nested try-except using the same variable name `e`. The outer try-except  contains a for loop, and inside the for loop is the second try-except  

In python, the variable assigned to the exception (`e` in this case) is deleted after exiting the try-except statement. So if the inner try-except triggers, it will define its exception to `e` and delete it after exiting its local scope. Now `e` does not exist.  So in the next iteration of the loop, the error will occur when `e` is referenced on line 255.

as of writing this line 255 is the below code:
```
if len(e.errors()) == 2 and num == 1 and error['type'] == 'type_error.none.allowed':
```

**To Reproduce**
Im not sure how to give concrete steps, as you might need a similar setting_fields.py override file and settings.py repo (explained more at the bottom of the report)

1. Have a settings repository with errors
2. Possibly a settings_fields.py override file in plugins that is faulty?
3. call the api with the below lines:
```
alias curlJ curl -k -s -H "Authorization: Bearer $JWT_AUTH_TOKEN" -H "Content-Type: application/json"
curlJ https://hostname/api/v1.0/repository/settings -d '{"action": "refresh"}' -X PUT | jq

```

**Expected behavior**
Return message from the API should give the real reason why the settings refresh did not work, i.e. what was wrong with the settings/settings_fields.

**Screenshots**
Not a screenshot, but the relevant lines from the log
```
2021-11-15 14:50:23,726 DEBG 'uwsgi' stdout output:
[2021-11-15 14:50:23,725] INFO in git: Trying to acquire lock for devices to run refresh repo: 64

2021-11-15 14:50:23,726 DEBG 'uwsgi' stdout output:

2021-11-15 14:50:24,061 DEBG 'uwsgi' stdout output:
[2021-11-15 14:50:24,061] DEBUG in git: Clearing redis-lru cache for settings

2021-11-15 14:50:24,089 DEBG 'uwsgi' stdout output:
[2021-11-15 14:50:24,088] DEBUG in settings: unhashable type: 'dict'

2021-11-15 14:50:24,089 DEBG 'uwsgi' stdout output:
[2021-11-15 14:50:24,089] ERROR in git: Exception while scheduling job for refresh repo: local variable 'e' referenced before assignment
Traceback (most recent call last):
  File "/opt/cnaas/venv/lib/python3.7/site-packages/redis_lru/lru.py", line 46, in inner
    return self[key]
  File "/opt/cnaas/venv/lib/python3.7/site-packages/redis_lru/lru.py", line 71, in __getitem__
    raise KeyError()
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./cnaas_nms/db/settings.py", line 247, in check_settings_syntax
    ret_dict = f_root(**settings_dict).dict()
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 4 validation errors for f_root
vrfs
  none is not an allowed value (type=type_error.none.not_allowed)
vxlans -> ztp -> dns_servers_6
  field required (type=value_error.missing)
vxlans -> ansatt -> dns_servers_6
  value is not a valid list (type=type_error.list)
slaac_dns_servers
  value is not a valid list (type=type_error.list)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./cnaas_nms/db/git.py", line 88, in refresh_repo
    result = _refresh_repo_task(repo_type)
  File "./cnaas_nms/db/git.py", line 170, in _refresh_repo_task
    get_settings()
  File "/opt/cnaas/venv/lib/python3.7/site-packages/redis_lru/lru.py", line 48, in inner
    result = func(*args, **kwargs)
  File "./cnaas_nms/db/settings.py", line 613, in get_settings
    verified_settings = check_settings_syntax(settings, settings_origin)
  File "./cnaas_nms/db/settings.py", line 255, in check_settings_syntax
    if len(e.errors()) == 2 and num == 1 and error['type'] == 'type_error.none.allowed':
UnboundLocalError: local variable 'e' referenced before assignment

2021-11-15 14:50:24,092 DEBG 'uwsgi' stdout output:
[2021-11-15 14:50:24,092] INFO in git: Releasing lock for devices from refresh repo job: 64

2021-11-15 14:50:24,156 DEBG 'uwsgi' stdout output:
[2021-11-15 14:50:24,156] INFO in app: User: cnaas, Method: PUT, Status: 500, URL: https://hostname/api/v1.0/repository/settings, JSON: {'action': 'refresh'}

2021-11-15 14:50:24,160 DEBG 'uwsgi' stdout output:
[pid: 17|app: 0|req: 5/5] 172.30.0.1 () {40 vars in 813 bytes} [Mon Nov 15 14:50:23 2021] PUT /api/v1.0/repository/settings => generated 103 bytes in 444 msecs (HTTP/1.1 500) 4 headers in 198 bytes (3 switches on core 999)

```

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 10 (buster) (lab host for running docker containers)

**Additional context**
This happened while overriding settings_fields.py, so its likely that there was something wrong with this file that caused exceptions to occur in the first place. The settings repo also contain a lot of changes that were not tested, so likely there are issues there as well, reflected by the logs containing several errors with the settings. This error occured while trying to test the settings_fields override file with our settings repository and figure out what is wrong, so I cant say for certain if both are broken or not.

I think this local variable error will only occur if there is something wrong with either the settings or the settings_fields. If there are no errors, the exceptions wont happen in the first place and there wont be a chance for the `e` variable to be referenced. 

** Proposed change **
Make it so the inner try-except block uses a different variable name for the exception than the outer block.

**Comment by indy-independence** [comment]
Fix merged in #221
